x-build: &default-build
  context: .
  dockerfile: Dockerfile.DevLocal

services:
  app:
    build:
      <<: *default-build
      target: app
    container_name: app
    volumes:
      - ./app:/opt/app/
    ports:
      - 8008:8008
    restart: on-failure
  neo4j:
    image: neo4j:5.20.0
    container_name: neo4jdb
    ports:
      - 7474:7474
      - 7475:7687
    restart: on-failure
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - ./neo4j_data/data:/data
      - ./neo4j_data/conf:/conf
      - ./neo4j_data/logs:/logs
      - ./neo4j_data/plugins:/plugins
