x-build: &default-build
  context: .
  dockerfile: Dockerfile.DevLocal

services:
  app:
    build:
      <<: *default-build
      target: app
    container_name: app
    volumes:
      - ./app:/opt/app/
    ports:
      - 8008:8008
    restart: on-failure
  neo4j:
    image: neo4j:5.20.0
    ports:
      - 7474:7474
      - 7475:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j_data/data:/data
      - ./neo4j_data/conf:/conf
      - ./neo4j_data/logs:/logs
      - ./neo4j_data/plugins:/plugins
