[development]
HUGGING_FACE_MODEL_NAME = 'mistralai/Mistral-7B-Instruct-v0.2'
HUGGING_FACE_EMBEDDINGS_MODEL_NAME="mixedbread-ai/mxbai-embed-large-v1"
LOCAL_MODEL_NAME="llama3"
LOCAL_EMBEDDINGS_MODEL_NAME=""
GROQ_MODEL_NAME='Llama3-70b-8192'
NEO4J_USER="neo4j"
NEO4J_PASSWORD="password" 
NEO4J_URI="neo4j://host.docker.internal:7475"
NEO4J_DATABASE="neo4j"
LANGCHAIN_TRACING_V2="true"