[development]
HUGGING_FACE_TOKEN = "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"
HUGGING_FACE_MODEL_NAME = 'mistralai/Mistral-7B-Instruct-v0.2'
HUGGING_FACE_EMBEDDINGS_MODEL_NAME="mixedbread-ai/mxbai-embed-large-v1"
LOCAL_MODEL_NAME="llama3"
LOCAL_EMBEDDINGS_MODEL_NAME=""
ASTRA_DB_APPLICATION_TOKEN="AstraCS:phZXBDUrnoDfeJsXLQyhPLIZ:43e0d082f849125897fb9dfbdf552c8025341596e56bb8c562c21d21118d12ec"
ASTRA_DB_ID="60205a29-8375-41a4-bafa-95e8de92c557"
GROQ_API_KEY="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"
GROQ_MODEL_NAME='Llama3-70b-8192'
NEO4J_USER="neo4j"
NEO4J_PASSWORD="password" 
NEO4J_URI="neo4j://host.docker.internal:7475"
NEO4J_DATABASE="neo4j"
GOOGLE_API_KEY="AIzaSyDMLgK_OUzBcq0BtWyK0WiNr6aEz0YsDjE"